// Generated by CoffeeScript 2.7.0
(function() {
  window.convert = function() {
    var converted, result, temp, type, unit;
    temp = parseFloat(document.getElementById("tempInput").value);
    type = document.getElementById("conversionType").value;
    result = document.getElementById("result");
    if (isNaN(temp)) {
      result.innerText = "Por favor, insira um número válido.";
      return;
    }
    converted = type === "toF" ? (temp * 9 / 5) + 32 : (temp - 32) * 5 / 9;
    unit = type === "toF" ? "°F" : "°C";
    return result.innerText = "Resultado: " + converted.toFixed(2) + " " + unit;
  };

}).call(this);
